# Popstore CI/CD pipeline for Heroku

#before_script:
#  - apt-get update -qy
#  - apt-get install -y ruby-dev
#  - gem install dpl

workflow:
    rules:
    - when: always

cache:
  paths:
    - node_modules/

stages:
  - init
  - test
  - build
  - deploy

init:
  stage: init
  image: node:14.19.0
  script:
    - npm install

test:
  stage: test
  image: node:14.19.0
  script:
    - export REACT_APP_API_KEY=$REACT_APP_API_KEY
    - export REACT_APP_AUTH_DOMAIN=$REACT_APP_AUTH_DOMAIN
    - export REACT_APP_PROJECT_ID=$REACT_APP_PROJECT_ID
    - export REACT_APP_STORAGE_BUCKET=$REACT_APP_STORAGE_BUCKET
    - export REACT_APP_MESSAGING_SENDER_ID=$REACT_APP_MESSAGING_SENDER_ID
    - export REACT_APP_ID=$REACT_APP_ID
    - export REACT_APP_MEASUREMENT=$REACT_APP_MEASUREMENT
    - export FAST_REFRESH=$FAST_REFRESH
    - export REACT_APP_CURRENCY_API_KEY=$REACT_APP_CURRENCY_API_KEY
    - export REACT_APP_EMAILJS_USER_ID=$REACT_APP_EMAILJS_USER_ID
    - export REACT_APP_EMAIL_JS_TOKEN=$REACT_APP_EMAIL_JS_TOKEN
    - export REACT_APP_EMAILJS_SERVICE_ID=$REACT_APP_EMAILJS_SERVICE_ID
    - export REACT_APP_EMAILJS_TEMPLATE_ID=$REACT_APP_EMAILJS_TEMPLATE_ID
    - export REACT_APP_STORE_LINK=$REACT_APP_STORE_LINK
    - echo "REACT_APP_STORE_LINK=$REACT_APP_STORE_LINK"
    - npm run test

build:
  stage: build
  image: node:14.19.0
  script:
    - export REACT_APP_API_KEY=$REACT_APP_API_KEY
    - export REACT_APP_AUTH_DOMAIN=$REACT_APP_AUTH_DOMAIN
    - export REACT_APP_PROJECT_ID=$REACT_APP_PROJECT_ID
    - export REACT_APP_STORAGE_BUCKET=$REACT_APP_STORAGE_BUCKET
    - export REACT_APP_MESSAGING_SENDER_ID=$REACT_APP_MESSAGING_SENDER_ID
    - export REACT_APP_ID=$REACT_APP_ID
    - export REACT_APP_MEASUREMENT=$REACT_APP_MEASUREMENT
    - export FAST_REFRESH=$FAST_REFRESH
    - export REACT_APP_CURRENCY_API_KEY=$REACT_APP_CURRENCY_API_KEY
    - export REACT_APP_EMAILJS_USER_ID=$REACT_APP_EMAILJS_USER_ID
    - export REACT_APP_EMAIL_JS_TOKEN=$REACT_APP_EMAIL_JS_TOKEN
    - export REACT_APP_EMAILJS_SERVICE_ID=$REACT_APP_EMAILJS_SERVICE_ID
    - export REACT_APP_EMAILJS_TEMPLATE_ID=$REACT_APP_EMAILJS_TEMPLATE_ID
    - export REACT_APP_STORE_LINK=$REACT_APP_STORE_LINK
    - npm run build
  artifacts:
    paths:
      - build/
    when: always
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual

deploy:
  stage: deploy
  image: node:14.19.0
  script:
    - npm i firebase-tools -g
    - firebase deploy --only hosting --token $FIREBASE_DEPLOY --project popsto-re --non-interactive
    - echo "Deployed to production server (Firebase Hosting)"
  environment:
    name: production
    url: https://popsto.re/
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual