# Popstore CI/CD pipeline for Heroku

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

cache:
  paths:
    - node_modules/

stages:
  - init
  - test
  - deploy
# - build # not needed for now as we are using heroku for deployment

init:
  stage: init
  image: node:14.19.0
  script:
    - npm install

test:
  stage: test
  image: node:14.19.0
  script:
    - npm run test

#build:
#  stage: init
#  image: node:14.19.0
#  script:
#    - npm run build
#  artifacts:
#    paths:
#      - build/
#    when: always

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=poolfarm --api-key=$HEROKU_API_KEY
    - echo "Deployed to production server"
  environment:
    name: production
    url: https://poolfarm.herokuapp.com/
  only:
    - main