# Popstore CI/CD pipeline for Heroku

cache:
  paths:
    - node_modules/

stages:
  - init
  - test
  #- build # not needed for now as we are using heroku for deployment
  - deploy

init:
  stage: init
  image: node:14.19.0
  script:
    - npm install

test:
  stage: test
  image: node:14.19.0
  script:
    - npm run test

#build:
#  stage: init
#  image: node:14.19.0
#  script:
#    - npm run build
#  artifacts:
#    paths:
#      - build/
#    when: always

deploy:
  stage: deploy
  image: node:14.19.0
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/poolfarm.git HEAD:master
    - echo "Deployed to production server"
    environment:
      name: production
      url: https://poolfarm.herokuapp.com/
    only:
      - master