on:
  push:
    branches:
      - main
      - popstoreV1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.19.0"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_ID: ${{ secrets.REACT_APP_ID }}
          REACT_APP_MEASUREMENT: ${{ secrets.REACT_APP_MEASUREMENT }}
          FAST_REFRESH: ${{ secrets.FAST_REFRESH }}

          REACT_APP_STORE_LINK: "https://popsto.re/v1/"
        run: npm run test

      - name: Build
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_ID: ${{ secrets.REACT_APP_ID }}
          REACT_APP_MEASUREMENT: ${{ secrets.REACT_APP_MEASUREMENT }}
          FAST_REFRESH: ${{ secrets.FAST_REFRESH }}
          REACT_APP_STORE_LINK: "https://popsto.re/v1/"
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1.2.0
        with:
          args: deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --project popsto-re --non-interactive
